version: '3.8'
services:
  db-lab:
    image: mysql:8.0
    container_name: tienda-mysql-lab
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: tienda_db
    volumes:
      - db_lab_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - lab-net

  db-usuarios-lab:
    image: mysql:8.0
    container_name: db-usuarios-lab
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: tienda_usuarios
    volumes:
      - db_usuarios_lab_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - lab-net

  app-lab:
    image: tiendaonline:latest
    container_name: tienda-app-lab
    ports:
      - "8083:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tienda-mysql-lab:3306/tienda_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_IMPORT-CHECK_ENABLED: "false"
    depends_on:
      db-lab:
        condition: service_healthy
    networks:
      - lab-net
      - eros-afrodita-web_app-net

  frontend-lab:
    image: eros-front:lab
    container_name: eros-frontend-lab
    ports:
      - "4002:80"
    volumes:
      - ./lab-assets-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-lab
    networks:
      - lab-net
      - eros-afrodita-web_app-net

volumes:
  db_lab_data:
  db_usuarios_lab_data:

networks:
  lab-net:
    name: eros-afrodita-lab-net
  eros-afrodita-web_app-net:
    external: true
