name: Tests en main

on:
  push:
    branches: [ main ] # Specify that this workflow only runs on pushes to the 'main' branch

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Recommended vendor for OpenJDK
          java-version: '25'
          cache: 'maven'

      - name: mvn validate
        run: mvn -B validate

      - name: mvn compilate
        run: mvn -B compile

      - name: mvn test
        run: mvn -B test

      - name: mvn package
        run: mvn -B package -DskipTests=true
