import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Divine Rose EDP",
    brand: "Chanel",
    price: "$120.00",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDa4Kt4I2NVtstPCSdDWDvlS-MJ4NROSowToJ0tsQy4At7egOy8irTpsCLP6vUnqHsF5k_1eYFTJT9z0LNq21eAwxfXf30NEIPCwmXxJR9RWhoCDdjXsQaGpBNTc4QWDWejTobRG5XI6eph_GpJ2P61JviUm4z1B9fcQS59mjpbUfAeMm2z4Nh4zMIUlUSP56cP4WC3O9w2aboXUM5pTCA2_zxDcNU3lrAAamIRp9T_W3WUWpCKCPjr7lZ_o8AF16OJUwUkUG7qeLsC",
    tag: "NUEVO",
    category: "floral",
    rating: 4.5,
  },
  {
    id: "2",
    name: "J'adore Gold Elixir",
    brand: "Dior",
    price: "$145.00",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJ5VP1YtIKRKNhJ_2DCgKFbyDmHdd2g2arcxXD-GQRr_iQLCaz8J0R-b-vzJ6RJq1C4LKJYeBse7S6apaxMq6vubJ2OHZabiFRrCWL-OUfWdHVJuqVMTXfCaNX-BxvBynFNszeIsF-KLpA4lHc0G13SzBsmbWASDyU2GlhtE6Lxx9x9OtFWMlu0fwHN6xDIWLGLzKyXSCzks5MUnYRIyRu7Csnv-gd_gXcPDGAIdqKZjSz5pPrx7v3PlbXdHZE4VeEW2C0l3PbwsOr",
    category: "floral",
    rating: 5,
  },
  {
    id: "3",
    name: "Black Opium Intense",
    brand: "YSL",
    price: "$108.00",
    originalPrice: "$135.00",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAE9UdBsb4uC-jOr1Lz_KLzu2sMiPSqaiHbMmw-mZAIKMwB3qjBvRmr9dKiC3W72-z2qiT3_xwVgJp6mw7l8qjDVgtbxrvi0qUB9uVfrRh6MBIffbbcal7NwgNrpSpTzYxrgoM-Kw_XXsL2L8l2J4ps3e36CzsB8bWtMpLATdLfj4dPmb8m0viqhvvk9ioulG1-eXn5cTaBPyXZsUoQoy7Wjp65s_83hFoYZ_UxWo6vR38U73Z_JIIiHvRg7aTylc56gobjlEm1hYTG",
    tag: "-20%",
    tagColor: "bg-red-500/90 text-white",
    category: "oriental",
    rating: 4.8,
  },
  {
    id: "4",
    name: "Flora Gorgeous Gardenia",
    brand: "Gucci",
    price: "$95.00",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCW1xOETRE7U730SWOYLv3YUCSmU72_Vz1Xorxbp_ivRVypPZDiZua5P9SNWrZZWecIeqw6BFb9q_GyAHz3G_Vu8oZ_crbxEwVMsuhsFukkccGhaIBON2gHb0XSRRiJWPI4CfpY13esyLKlFCEAknLL6NjGu8CllV47sdA5UxL_xGlfYm3YbyNqc5-rS-ql5fkZFh8mYkkB4VgoXnnH9r6ijhoWILlvPQrYhvoC1OgOksZ8DwA1UrO_CW9h4J_vEyfs098EIuCi9J6J",
    category: "citrico",
    rating: 4.2,
  },
  {
    id: "5",
    name: "Oud Wood",
    brand: "Tom Ford",
    price: "$240.00",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCDlPHAMh8mOdVcgzrFbsscFu7z4uEM1ONh7cKXT_kBsUTYhACyJ_d_j1TNe4NcXur_BHhJzMY8SQx0AliH0lICNysHB0SLeYY-9JSYgR62YH1ybAQ_wb6SFgUCGWjRZ_B3BpdBKYxFFtz6gGcOjNBiGDzfuZMSYyJmOpJHOClXpnRvFpqCQOxqb6YbSAQjMEzEwGRrmQu5juzQQwFsK1U4PLuEtBofADTgJH4e2fJ2_SLluD3SVv_2yKeS20WwtiXOxuWb-pIWW-y6",
    category: "amaderado",
    rating: 4.9,
  },
  {
    id: "6",
    name: "Sauvage Elixir",
    brand: "Dior",
    price: "$155.00",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFObjwh2RN28D1F4TX5S2pHcV98QIhH0YAEEufV0lrRugYow0EhbhIJFJgKJ5tZNov8_igq9UnWCkGq3VeC1CSANJd3m6KV1Hws-C42iRIMr7UBphiW_7TgOTQomKeVCs2KV7bTBPcTxkMcx87Fv_I2xuoMd1W9dNtCCIgAKxBO5f4Sl6kO3B1yu2dTAJ9s8eGSThaU9W9hOVF71NDjCfUAvhB_tdpMNVzbiNVxmV96XxQ2XwdGr8tIzaSrMglvqbhOSoUgPnCQhpi",
    category: "amaderado",
    rating: 4.7,
  },
  {
    id: "7",
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    price: "$88.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    tag: "TOP VENTAS",
    category: "citrico",
    rating: 4.6,
  },
  {
    id: "8",
    name: "La Vie Est Belle",
    brand: "Lancôme",
    price: "$105.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "floral",
    rating: 4.9,
  },
  {
    id: "9",
    name: "Noir de Noir",
    brand: "Tom Ford",
    price: "$230.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "oriental",
    rating: 4.8,
  },
  {
    id: "10",
    name: "Chance Eau Tendre",
    brand: "Chanel",
    price: "$115.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "floral",
    rating: 4.5,
  },
  {
    id: "11",
    name: "Bleu de Chanel",
    brand: "Chanel",
    price: "$130.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "amaderado",
    rating: 4.7,
  },
  {
    id: "12",
    name: "L'Homme Intense",
    brand: "YSL",
    price: "$118.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "oriental",
    rating: 4.4,
  },
  {
    id: "13",
    name: "Idôle Nectar",
    brand: "Lancôme",
    price: "$99.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "oriental",
    rating: 4.3,
  },
  {
    id: "14",
    name: "The One",
    brand: "Dolce & Gabbana",
    price: "$110.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "oriental",
    rating: 4.6,
  },
  {
    id: "15",
    name: "Good Girl Blush",
    brand: "Carolina Herrera",
    price: "$125.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "floral",
    rating: 4.7,
  },
  {
    id: "16",
    name: "Light Blue Intense",
    brand: "Dolce & Gabbana",
    price: "$95.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "amaderado",
    rating: 4.5,
  },
  {
    id: "17",
    name: "Joy",
    brand: "Dior",
    price: "$112.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "floral",
    rating: 4.1,
  },
  {
    id: "18",
    name: "Eros Flame",
    brand: "Versace",
    price: "$102.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "amaderado",
    rating: 4.4,
  },
  {
    id: "19",
    name: "Boss Bottled Night",
    brand: "Hugo Boss",
    price: "$89.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "amaderado",
    rating: 4.0,
  },
  {
    id: "20",
    name: "Aventus",
    brand: "Creed",
    price: "$320.00",
    img: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
    tag: "EXCLUSIVO",
    category: "amaderado",
    rating: 4.9,
  },
];
